### ISSUE TITLE
Incompatible with Feathers v3: app.service('x').filter has been depreciated

### ISSUE THREAD

**Issue by leedongwei** [feathersjs/feathers-offline-publication#9]
Getting an error here when using with Feathers v3.

https://github.com/feathers-plus/feathers-offline-publication/blob/23d8eecfb70d94f4c2d4bbee9db0d17810109440/src/server/index.js#L19

**Comment by eddyystop** [comment]
The repo was designed for the channel design in Auk and it will not work with Buzzard.

It unfortunately will be several months before I have the time to look into this, because of other Feathers work related to Buzzard.

I would be delighted to get a PR should you decide to make it Buzzard compatible.

**Comment by leedongwei** [comment]
That's understandable, thanks for the quick response! 

Using Buzzard's channels will reduce the number of service events being sent to the clients - which is the primary purpose for this package. I'm not sure if it'll be worth your effort to make this compatible.

**Comment by eddyystop** [comment]
The primary purpose of this repo was to let the client dynamically determine what events it receives, rather than having that hardcoded on the server in the channels.

I don't see the Buzzard channels allowing that. Please let me know if I'm wrong.

**Comment by leedongwei** [comment]
You're right, Buzzard channels does not allow clients to subscribe/unsubscribe to events in a straightforward manner. So far, I've managed to get clients to dynamically sub/unsub to channels with some tricks, and then watching the changes with feathers-reactive. 

I'm still exploring the options to replicate data on the client and haven't figured out a simple solution. - a pub/sub pattern with rooms would greatly simplify things. I'll keep this repo in mind, though I'm not sure if I'll be able to contribute.

I get to my open issue in feathers-hooks-common about the VM this weekend :)
